# Filename: .travis.yml

language: python

python:
  - "3.4"

os:
  - linux

# command to run tests
script: make cover

# Install the codecov pip dependency
install:
  - pip install codecov
# Push the results back to codecov
after_success:
  - codecov
