# Filename: .travis.yml
---
language: python
python:
  - "3.6"
os: linux
dist: bionic

# Install the codecov and sphinx pip dependencies
jobs:
  include:
    - stage: lint
      name: "Pylint"
      install:
        - pip install pylint
        - sudo apt-get install -qy bc
      script: set -o pipefail ; (pylint myeda --rcfile .pylintrc | tee .pylint.log) || sed -re "s_.* ([0-9\.]+)/10.*_\1>3_;t;d" .pylint.log ; sed --version ; cat .pylint.log | wc -l
      #script: set -o pipefail ; (pylint myeda --rcfile .pylintrc | tee .pylint.log) || (test $(bc -l <<< $(sed -re "s_.* ([0-9\.]+)/10.*_\1>3_;t;d" .pylint.log)) -eq 1)
    - stage: cover
      name: "Codecov"
      install:
        - pip install codecov
      script: "make cover"
      after_success:
        - codecov
    - stage: doc
      name: "Sphinx"
      install:
        - pip install travis-sphinx
      script: "travis-sphinx build --source=doc/source"
      after_success:
        - travis-sphinx deploy
