# Filename: .travis.yml
---
language: python
python:
  - "3.6"
os: linux
dist: xenial

# Install the codecov and sphinx pip dependencies
install:
  - pip install codecov
  - pip install travis-sphinx

jobs:
  include:
    - stage: cover
      name: "Codecov"
      script: "make cover"
      after_success:
        - codecov
    - stage: doc
      name: "Sphinx"
      script: "travis-sphinx build --source=doc/source"
      after_success:
        - travis-sphinx deploy
