# Filename: .travis.yml

language: python

python:
  - "3.4"

os:
  - linux

# command to run tests
script: make test

# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
#script:
#  - coverage run tests.py

# Push the results back to codecov
after_success:
  - codecov
